### ISSUE TITLE
Build breaks in go:tip (1.5)

### ISSUE THREAD

**Issue by kyleterry** [kyleterry/tenyks#52]
```
Using worker: worker-linux-027f0490-2.bb.travis-ci.org:travis-linux-2

Build system information
Build language: go
Build image provisioning date and time
Wed Feb  4 18:22:50 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
Linux Version
2.6.32-042stab090.5
Cookbooks Version
23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"

$ git clone --depth=50 --branch=master git://github.com/kyleterry/tenyks.git kyleterry/tenyks
Cloning into 'kyleterry/tenyks'...
remote: Counting objects: 360, done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 360 (delta 178), reused 312 (delta 146), pack-reused 0
Receiving objects: 100% (360/360), 216.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (178/178), done.
Checking connectivity... done.
$ cd kyleterry/tenyks
$ git checkout -qf 3de7f1d07ca3ac335cfef32050bafcf2d5ade3ae
Installing gimme from https://raw.githubusercontent.com/meatballhat/gimme/v0.2.3/gimme
$ eval "$(gimme tip)"
go version devel +80864cf Fri May 29 04:33:15 2015 +0000 linux/amd64
$ export GOPATH=$HOME/gopath
$ export PATH=$HOME/gopath/bin:$PATH
$ mkdir -p $HOME/gopath/src/github.com/kyleterry/tenyks
$ rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/kyleterry/tenyks/
$ export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/kyleterry/tenyks
$ cd $HOME/gopath/src/github.com/kyleterry/tenyks
$ gimme version
v0.2.3
$ go version
go version devel +80864cf Fri May 29 04:33:15 2015 +0000 linux/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go"
GOTOOLDIR="/home/travis/.gimme/versions/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
$ go get ./...
$ go get code.google.com/p/gomock/gomock
$ go test ./...
?   	github.com/kyleterry/tenyks	[no test files]
ok  	github.com/kyleterry/tenyks/config	0.004s
?   	github.com/kyleterry/tenyks/control	[no test files]
2015/05/29 06:09:23 [mockirc] Disconnect called
2015/05/29 06:09:23 [mockirc] Starting send loop
2015/05/29 06:09:23 [mockirc] Stopping send loop
2015/05/29 06:09:23 accept tcp [::]:26661: use of closed network connection
2015/05/29 06:09:24 [mockirc] Bootstrapping connection
2015/05/29 06:09:24 [mockirc] Starting send loop
2015/05/29 06:09:24 <nil>
2015/05/29 06:09:24 USER tenyks localhost something :tenyks
2015/05/29 06:09:24 [mockirc] Sending PING to server 
2015/05/29 06:09:25 <nil>
2015/05/29 06:09:25 Nothing to do for NICK tenyks
2015/05/29 06:09:25 NICK tenyks
2015/05/29 06:09:25 <nil>
2015/05/29 06:09:25 PING 
2015/05/29 06:09:25 [mockirc] Disconnect called
2015/05/29 06:09:25 accept tcp [::]:26661: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5844b0]

goroutine 24 [running]:
github.com/kyleterry/tenyks/mockirc.(*MockIRC).connectionWorker(0xc2080205a0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:97 +0x410
created by github.com/kyleterry/tenyks/mockirc.(*MockIRC).Start.func1
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:69 +0x152

goroutine 1 [chan receive]:
testing.RunTests(0x784a88, 0x86f940, 0xa, 0xa, 0x1)
	/home/travis/.gimme/versions/go/src/testing/testing.go:563 +0xa7e
testing.(*M).Run(0xc208051f38, 0xc208014ae0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:492 +0x73
main.main()
	github.com/kyleterry/tenyks/irc/_test/_testmain.go:72 +0x119

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1670 +0x1

goroutine 16 [chan receive]:
github.com/kyleterry/tenyks/mockirc.(*MockIRC).Stop(0xc2080205a0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:88 +0xd7
github.com/kyleterry/tenyks/irc.TestCanHandshakeAndWorkWithIRC(0xc20801e5a0)
	/home/travis/gopath/src/github.com/kyleterry/tenyks/irc/connection_test.go:128 +0xaa7
testing.tRunner(0xc20801e5a0, 0x86f9a0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:454 +0x9b
created by testing.RunTests
	/home/travis/.gimme/versions/go/src/testing/testing.go:562 +0xa3e

goroutine 19 [runnable]:
github.com/kyleterry/tenyks/mockirc.(*MockIRC).Start.func1.1.1(0xc2080205a0, 0xc20801ca80)
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:58 +0x170
created by github.com/kyleterry/tenyks/mockirc.(*MockIRC).Start.func1.1
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:60 +0x64

goroutine 11 [chan send]:
github.com/kyleterry/tenyks/mockirc.(*MockIRC).Start.func1.1.1(0xc208020370, 0xc20801c720)
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:58 +0x170
created by github.com/kyleterry/tenyks/mockirc.(*MockIRC).Start.func1.1
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:60 +0x64

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7f844149f5f8, 0x72, 0xc20800a240)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:157 +0x63
net.(*pollDesc).Wait(0xc20801b560, 0x72, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*pollDesc).WaitRead(0xc20801b560, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/fd_poll_runtime.go:78 +0x3d
net.(*netFD).Read(0xc20801b500, 0xc2080b2000, 0x1000, 0x1000, 0x0, 0x7f844149a050, 0xc20800a240)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:233 +0x23d
net.(*conn).Read(0xc208030138, 0xc2080b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/net.go:124 +0xe7
bufio.(*Reader).fill(0xc20801cb40)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:97 +0x1ec
bufio.(*Reader).ReadSlice(0xc20801cb40, 0x584d0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:328 +0x21d
bufio.(*Reader).ReadBytes(0xc20801cb40, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:407 +0xae
bufio.(*Reader).ReadString(0xc20801cb40, 0xc20800ba0a, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:447 +0x50
github.com/kyleterry/tenyks/mockirc.(*MockIRC).connectionWorker(0xc2080205a0, 0x7f844149f860, 0xc208030138)
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:99 +0x264
created by github.com/kyleterry/tenyks/mockirc.(*MockIRC).Start.func1
	/home/travis/gopath/src/github.com/kyleterry/tenyks/mockirc/mockirc.go:69 +0x152

goroutine 23 [chan receive]:
github.com/kyleterry/tenyks/irc.(*Connection).send.func1(0xc20809c380, 0xc20801cc60)
	/home/travis/gopath/src/github.com/kyleterry/tenyks/irc/connection.go:170 +0x2e8
created by github.com/kyleterry/tenyks/irc.(*Connection).send
	/home/travis/gopath/src/github.com/kyleterry/tenyks/irc/connection.go:174 +0x64
FAIL	github.com/kyleterry/tenyks/irc	3.010s
ok  	github.com/kyleterry/tenyks/mockirc	0.004s
?   	github.com/kyleterry/tenyks/service	[no test files]
?   	github.com/kyleterry/tenyks/tenyksctl	[no test files]
?   	github.com/kyleterry/tenyks/version	[no test files]

The command "go test ./..." exited with 1.

Done. Your build exited with 1.
```

**Comment by kyleterry** [comment]
not no mo
